# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    container: ultrarangers/android-build:sdk-29
    runs-on: ubuntu-latest

    steps:
    - name: APT update
      run: apt update
    - name: Install pip3
      run: apt -y install python3-pip
    - name: Upgrade pip3
      run: pip3 install --upgrade pip setuptools wheel
    - name: Install cmake 3.14.4
      run: pip3 install 'cmake==3.14.4'
    - name: Install ninja
      run: pip3 install ninja
    - name: Configure Git for HTTPS
      run: git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
    - uses: actions/checkout@v2
    - name: Update submodules recursively
      run: git submodule sync --recursive && git submodule update --init --recursive --depth 1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew --info assembleDebug
